import Head from 'next/head';

export default function Index() {
  return (
    <div>
      <Head>
        <title>Coins Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Hello to criptoWorld</p>
      </main>


    </div>
  )
}
